# Generated by Django 4.2.14 on 2024-08-07 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mds_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 7, 18, 46, 41, 360079),
                verbose_name="дата и время приема",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="записи",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пациент",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="direction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mds_service.direction",
                verbose_name="направление",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(verbose_name="артикул"),
        ),
    ]
